In [173]:
import numpy as np

EJERCICIO 1: Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [174]:
array = np.random.rand(2,3,5)
array

array([[[0.81866412, 0.2849072 , 0.08879425, 0.78707065, 0.41191061],
        [0.62893865, 0.33902714, 0.98845751, 0.78523378, 0.29441076],
        [0.48612705, 0.92302605, 0.00837976, 0.34190492, 0.44154843]],

       [[0.51598591, 0.15035509, 0.08862013, 0.12175701, 0.04014771],
        [0.38489456, 0.12334507, 0.99463808, 0.9876757 , 0.58023486],
        [0.75191953, 0.74034108, 0.65941622, 0.83074743, 0.89334347]]])

In [175]:
array = np.round(array, decimals=1)
array

array([[[0.8, 0.3, 0.1, 0.8, 0.4],
        [0.6, 0.3, 1. , 0.8, 0.3],
        [0.5, 0.9, 0. , 0.3, 0.4]],

       [[0.5, 0.2, 0.1, 0.1, 0. ],
        [0.4, 0.1, 1. , 1. , 0.6],
        [0.8, 0.7, 0.7, 0.8, 0.9]]])

EJERCICIO 2: Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [176]:
media = np.round(np.mean(array), decimals=1)
media

0.5

EJERCICIO 3: Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [177]:
v_max= np.round(np.max(array), decimals=1)
v_max

1.0

EJERCICIO 4: Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [178]:
v_min= np.round(np.min(array), decimals=1)
v_min

0.0

EJERCICIO 5: Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

In [179]:
array_vacio = np.empty_like(array, str)
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [180]:
for m in range((array.shape)[0]):

    for f in range((array.shape)[1]):

        for c in range((array.shape)[2]):

            if array[m][f][c] == v_max:
                array_vacio[m][f][c] = "D"
            
            elif array[m][f][c] == v_min:
                array_vacio[m][f][c] = "E"

            elif array[m][f][c] == media:
                array_vacio[m][f][c] = "A"

            elif array[m][f][c] > media:
                array_vacio[m][f][c] = "B"
            
            elif array[m][f][c] < media:
                array_vacio[m][f][c] = "C"

            
            

print(array_vacio)

[[['B' 'C' 'C' 'B' 'C']
  ['B' 'C' 'D' 'B' 'C']
  ['A' 'B' 'E' 'C' 'C']]

 [['A' 'C' 'C' 'C' 'E']
  ['C' 'C' 'D' 'D' 'B']
  ['B' 'B' 'B' 'B' 'B']]]


Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [181]:
array_vacio_1 = array_vacio.reshape(30,)
array_vacio_1

array(['B', 'C', 'C', 'B', 'C', 'B', 'C', 'D', 'B', 'C', 'A', 'B', 'E',
       'C', 'C', 'A', 'C', 'C', 'C', 'E', 'C', 'C', 'D', 'D', 'B', 'B',
       'B', 'B', 'B', 'B'], dtype='<U1')

In [182]:
array_uni_vacio = np.empty(30)
array_uni_vacio

array([0.8, 0.3, 0.1, 0.8, 0.4, 0.6, 0.3, 1. , 0.8, 0.3, 0.5, 0.9, 0. ,
       0.3, 0.4, 0.5, 0.2, 0.1, 0.1, 0. , 0.4, 0.1, 1. , 1. , 0.6, 0.8,
       0.7, 0.7, 0.8, 0.9])

In [183]:
for m in range(30):


    if (array_vacio_1[m] == "A") or (array_vacio_1[m] == "B"):
        array_uni_vacio[m] = 1

              
    elif (array_vacio_1[m] == "C") or (array_vacio_1[m] == "D"):
        array_uni_vacio[m] = 2

    elif array_vacio_1[m] == "E":
        array_uni_vacio[m] = 3
          

            
            

print(array_uni_vacio)

[1. 2. 2. 1. 2. 1. 2. 2. 1. 2. 1. 1. 3. 2. 2. 1. 2. 2. 2. 3. 2. 2. 2. 2.
 1. 1. 1. 1. 1. 1.]


In [184]:
array_numero = array_uni_vacio.reshape(2,3,5)
array_numero

array([[[1., 2., 2., 1., 2.],
        [1., 2., 2., 1., 2.],
        [1., 1., 3., 2., 2.]],

       [[1., 2., 2., 2., 3.],
        [2., 2., 2., 2., 1.],
        [1., 1., 1., 1., 1.]]])