In [1]:
import numpy as np

EJERCICIO 1: ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [2]:
np.random.seed(42)
array_sample1=np.random.random_sample((3,4))
array_sample1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [3]:
np.random.seed(42)
array_sample2=np.random.random_sample((3,4))
array_sample2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

EJERCICIO 2: Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [4]:
array_int=np.random.randint(0,10,(2,3,5))
array_int

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4]],

       [[2, 6, 4, 8, 6],
        [1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3]]])

In [5]:
val_unicos=np.unique(array_int)
print(f"Los valores únicos del array son: {val_unicos}")

Los valores únicos del array son: [0 1 2 3 4 5 6 8 9]


In [6]:
array_bino=np.random.binomial(10,0.3, size=(2,3,5))
print("El número de veces que salió 1 es: ")
print(array_bino)

El número de veces que salió 1 es: 
[[[2 4 3 4 2]
  [3 2 4 3 2]
  [3 1 4 3 3]]

 [[5 4 2 3 3]
  [6 4 4 3 3]
  [6 3 2 2 2]]]


In [7]:
bino_unicos=np.unique(array_bino)
print(f"Los valores únicos del array binomial son: {bino_unicos}")

Los valores únicos del array binomial son: [1 2 3 4 5 6]


EJERCICIO 3: En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos.

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [8]:
comun_arrays=np.intersect1d(val_unicos,bino_unicos)
print(f"Los valores únicos entre los arrays son: {comun_arrays}")

Los valores únicos entre los arrays son: [1 2 3 4 5 6]


In [9]:
union_arrays=np.union1d(val_unicos,bino_unicos)
print(f"La unión de los 2 arrays es: {union_arrays}")

La unión de los 2 arrays es: [0 1 2 3 4 5 6 8 9]


In [10]:
dif_val_bino=np.setdiff1d(val_unicos,bino_unicos)
print(f"La diferencia de elementos entre los valores únicos del array val_unicos y bino_unicos es: {dif_val_bino}")

La diferencia de elementos entre los valores únicos del array val_unicos y bino_unicos es: [0 8 9]


EJERCICIO 4: Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [11]:
array1=np.random.randint (1,100,(80))
array1

array([89, 71,  9, 88,  1,  8, 88, 63, 11, 81,  8, 35, 35, 33,  5, 41, 28,
        7, 73, 72, 12, 34, 33, 48, 23, 62, 88, 37, 99, 44, 86, 91, 35, 65,
       99, 47, 78,  3,  1,  5, 90, 14, 27,  9, 79, 15, 90, 42, 77, 51, 63,
       96, 52, 96,  4, 94, 23, 15, 43, 29, 36, 13, 32, 71, 59, 86, 28, 66,
       42, 45, 62, 57,  6, 28, 28, 44, 84, 30, 62, 75])

In [12]:
array2=np.random.randint (1,100,(80))
array2

array([92, 89, 62, 97,  1, 27, 62, 77,  3, 70, 72, 27,  9, 62, 37, 97, 51,
       44, 24, 79, 59, 32, 96, 88, 52, 62, 58, 52, 12, 39,  2,  3, 56, 81,
       59,  2,  2, 92, 54, 87, 96, 97,  1, 19,  2, 53, 44, 90, 32, 70, 32,
       68, 55, 75, 56, 17, 38, 24, 69, 98, 70, 86, 11, 16, 97, 73, 59, 70,
       80, 93,  3, 20, 59, 36, 19, 90, 67, 19, 20, 96])

In [13]:
array1=np.unique(array1)
array1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 23, 27, 28, 29,
       30, 32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 47, 48, 51, 52, 57,
       59, 62, 63, 65, 66, 71, 72, 73, 75, 77, 78, 79, 81, 84, 86, 88, 89,
       90, 91, 94, 96, 99])

In [14]:
array2=np.unique(array2)
array2

array([ 1,  2,  3,  9, 11, 12, 16, 17, 19, 20, 24, 27, 32, 36, 37, 38, 39,
       44, 51, 52, 53, 54, 55, 56, 58, 59, 62, 67, 68, 69, 70, 72, 73, 75,
       77, 79, 80, 81, 86, 87, 88, 89, 90, 92, 93, 96, 97, 98])

In [15]:
array3=np.setdiff1d(array1,array2)
print(f"Los valores que tenemos en el array1 y no en el array2 son: {array3}")

Los valores que tenemos en el array1 y no en el array2 son: [ 4  5  6  7  8 13 14 15 23 28 29 30 33 34 35 41 42 43 45 47 48 57 63 65
 66 71 78 84 91 94 99]


In [16]:
array4=np.setdiff1d(array2,array1)
print(f"Los valores que tenemos en el array2 y no en el array1 son: {array4}")

Los valores que tenemos en el array2 y no en el array1 son: [ 2 16 17 19 20 24 38 39 53 54 55 56 58 67 68 69 70 80 87 92 93 97 98]


In [17]:
array5=np.intersect1d(array1,array2)
print(f"La intersección del array1 y el array2 es:")
print(array5)

La intersección del array1 y el array2 es:
[ 1  3  9 11 12 27 32 36 37 44 51 52 59 62 72 73 75 77 79 81 86 88 89 90
 96]


¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [18]:
# el array 1 y el array 2 fueron creados con la misma longitud pero al crearlo random podemos ver que 
# el array 1 tiene más valores únicos que el array 2

In [19]:
array1.size

56

In [20]:
array2.size

48

In [22]:
# en el array 3 podemos ver los elementos  que estan en el 1 pero no en el 2
array3.size

31

In [24]:
# en el array 4 podemos ver los elementos  que estan en el 2 pero no en el 1
array4.size

23

In [26]:
# en el array 4 podemos ver los elementos comunes en ambos arrays
array5.size

25

In [27]:
print(f'tamaño de array1: {len(array1)}')
print(f'tamaño de array2: {len(array2)}')


dif1_inter = np.add(len(array3),len(array5))
print(f'El resultado de sumar el tamaño del array de los valores que solo están en el array1 y el intercepto es: {dif1_inter}, el cual es igual al tamaño del array1')

dif2_inter = np.add(len(array4),len(array5))
print(f'El resultado de sumar el tamaño del array de los valores que solo están en el array2 y el intercepto es: {dif2_inter}, el cual es igual al tamaño del array2')

tamaño de array1: 56
tamaño de array2: 48
El resultado de sumar el tamaño del array de los valores que solo están en el array1 y el intercepto es: 56, el cual es igual al tamaño del array1
El resultado de sumar el tamaño del array de los valores que solo están en el array2 y el intercepto es: 48, el cual es igual al tamaño del array2
