In [1]:
import numpy as np

EJERCICIO 1: ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [23]:
np.random.seed(42)
array_sample1=np.random.random_sample((3,4))
array_sample1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [24]:
np.random.seed(42)
array_sample2=np.random.random_sample((3,4))
array_sample2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

EJERCICIO 2: Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [25]:
array_int=np.random.randint(0,10,(2,3,5))
array_int

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4]],

       [[2, 6, 4, 8, 6],
        [1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3]]])

In [12]:
val_unicos=np.unique(array_int)
print(f"Los valores únicos del array son: {val_unicos}")

Los valores únicos del array son: [0 1 2 3 4 5 6 8 9]


In [26]:
array_bino=np.random.binomial(10,0.3, size=(2,3,5))
print("El número de veces que salió 1 es: ")
print(array_bino)

El número de veces que salió 1 es: 
[[[2 4 3 4 2]
  [3 2 4 3 2]
  [3 1 4 3 3]]

 [[5 4 2 3 3]
  [6 4 4 3 3]
  [6 3 2 2 2]]]


In [29]:
bino_unicos=np.unique(array_bino)
print(f"Los valores únicos del array binomial son: {bino_unicos}")

Los valores únicos del array binomial son: [1 2 3 4 5 6]


EJERCICIO 3: En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos.

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [30]:
comun_arrays=np.intersect1d(val_unicos,bino_unicos)
print(f"Los valores únicos entre los arrays son: {comun_arrays}")

Los valores únicos entre los arrays son: [1 2 3 4 5 6]


In [31]:
union_arrays=np.union1d(val_unicos,bino_unicos)
print(f"La unión de los 2 arrays es: {union_arrays}")

La unión de los 2 arrays es: [0 1 2 3 4 5 6 8 9]


In [35]:
dif_val_bino=np.setdiff1d(val_unicos,bino_unicos)
print(f"La diferencia de elementos entre los valores únicos del array val_unicos y bino_unicos es: {dif_val_bino}")

La diferencia de elementos entre los valores únicos del array val_unicos y bino_unicos es: [0 8 9]


EJERCICIO 4: Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [41]:
array1=np.random.randint (1,100,(80))
array1

array([27, 98, 21, 30, 97, 28, 64, 97, 69, 61, 48, 19,  4, 35, 64, 49, 17,
       44, 92, 30, 93, 46,  6, 99, 37, 24, 93, 46, 53, 95, 99, 60, 97, 63,
       85, 32, 87, 33, 67, 18, 25, 95, 54, 58, 67, 46, 24, 32, 47, 86, 23,
       66, 27,  2, 90, 17, 33,  9, 43, 48, 39, 93, 42, 26, 99, 50, 25, 24,
       13, 60,  7, 57, 36, 45, 20, 65,  8, 16, 14, 76])

In [42]:
array2=np.random.randint (1,100,(80))
array2

array([87, 15, 92, 98, 66, 32, 87, 63, 86, 51, 25, 58, 63, 62, 22, 58, 58,
       86, 49, 52, 42, 70, 15, 54, 60, 97,  8, 53, 60,  5, 68,  6, 96, 94,
       47, 99, 55, 40, 52, 16, 13, 30, 19, 17, 63, 19, 92, 58, 55, 90, 90,
       62, 23,  9, 12,  1, 58,  1, 34, 96, 48, 89,  1, 16, 61, 64, 63, 69,
       22, 93, 67, 76, 26, 16, 51, 86, 57, 29, 78, 92])

In [43]:
array1=np.unique(array1)
array1

array([ 2,  4,  6,  7,  8,  9, 13, 14, 16, 17, 18, 19, 20, 21, 23, 24, 25,
       26, 27, 28, 30, 32, 33, 35, 36, 37, 39, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 53, 54, 57, 58, 60, 61, 63, 64, 65, 66, 67, 69, 76, 85, 86,
       87, 90, 92, 93, 95, 97, 98, 99])

In [44]:
array2=np.unique(array2)
array2

array([ 1,  5,  6,  8,  9, 12, 13, 15, 16, 17, 19, 22, 23, 25, 26, 29, 30,
       32, 34, 40, 42, 47, 48, 49, 51, 52, 53, 54, 55, 57, 58, 60, 61, 62,
       63, 64, 66, 67, 68, 69, 70, 76, 78, 86, 87, 89, 90, 92, 93, 94, 96,
       97, 98, 99])

In [45]:
array3=np.setdiff1d(array1,array2)
print(f"Los valores que tenemos en el array1 y no en el array2 son: {array3}")

Los valores que tenemos en el array1 y no en el array2 son: [ 2  4  7 14 18 20 21 24 27 28 33 35 36 37 39 43 44 45 46 50 65 85 95]


In [46]:
array4=np.setdiff1d(array2,array1)
print(f"Los valores que tenemos en el array2 y no en el array1 son: {array4}")

Los valores que tenemos en el array2 y no en el array1 son: [ 1  5 12 15 22 29 34 40 51 52 55 62 68 70 78 89 94 96]


In [52]:
array5=np.intersect1d(array1,array2)
print(f"La intersección del array1 y el array2 es:")
print(array5)

La intersección del array1 y el array2 es:
[ 6  8  9 13 16 17 19 23 25 26 30 32 42 47 48 49 53 54 57 58 60 61 63 64
 66 67 69 76 86 87 90 92 93 97 98 99]


¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.