In [2]:
import numpy as np

EJERCICIO 1
Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
array_dim_1 = np.random.randint(0,100,(5))
array_dim_1

array([37, 41, 71, 88, 21])

In [4]:
array_dim_2 = np.random.rand(2,3)
array_dim_2

array([[0.22864028, 0.22048497, 0.98256129],
       [0.96356184, 0.34101803, 0.89582658]])

In [5]:
array_dim_3 = np.random.rand(2,3,5)

In [6]:
array_dim_3

array([[[0.20880422, 0.81260466, 0.40453392, 0.6737085 , 0.48663074],
        [0.83901165, 0.01386405, 0.7275015 , 0.86372151, 0.96249253],
        [0.30437741, 0.80218722, 0.64489902, 0.11074599, 0.69488041]],

       [[0.81996912, 0.90879722, 0.55808047, 0.39952058, 0.73471978],
        [0.98150542, 0.09735613, 0.96525049, 0.64720878, 0.96786909],
        [0.69627074, 0.80373874, 0.92444437, 0.69303178, 0.80452376]]])

EJERCICIO 2:Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [7]:
def propiedades (array):
    print(f"La forma del array: {array.shape}")
    print(f"El tamaño del array: {array.size}")
    print(f"Las dimenciones del array: {array.ndim}")
    print(f"El tipo de dato del array: {array.dtype}")

In [8]:
propiedades(array_dim_1)

La forma del array: (5,)
El tamaño del array: 5
Las dimenciones del array: 1
El tipo de dato del array: int64


In [9]:
propiedades(array_dim_2)

La forma del array: (2, 3)
El tamaño del array: 6
Las dimenciones del array: 2
El tipo de dato del array: float64


In [10]:
propiedades(array_dim_3)

La forma del array: (2, 3, 5)
El tamaño del array: 30
Las dimenciones del array: 3
El tipo de dato del array: float64


EJERCICIO 3 :Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [24]:
matriz=np.identity(3)
print(matriz)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


EJERCICIO 4:Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [26]:
matriz_unos=np.ones_like(array_dim_3)
print(matriz_unos)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


EJERCICIO 5: Es el momento de hacer algunas operaciones entre arrays
¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. - La solución puede ser crear un array nuevo.
- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
- Dividid las dos matricess


In [27]:
np.add(array_dim_2, matriz)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

Como el shape es distintos en una y la otra no se pueden sumar ya que tienes que tener la misma forma.

In [40]:
#Este array lo creamos paraa solucionar el problema anterior
array_suma=np.random.randint(1,5,(3,3))

suma=np.add(array_suma,matriz)
print(f"La suma es:")
print(suma)

[[2 2 4]
 [3 2 2]
 [2 1 4]]
---------------------------
La suma es:
[[3. 2. 4.]
 [3. 3. 2.]
 [2. 1. 5.]]


In [41]:
multi=np.multiply(matriz,suma)
print(f"La multiplicación es:")
print(multi)

La multiplicación es:
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 5.]]


In [43]:
divi=np.divide(matriz,array_suma)

In [46]:
print("La división es:")
print(divi)

La división es:
[[0.5  0.   0.  ]
 [0.   0.5  0.  ]
 [0.   0.   0.25]]
