In [2]:
import numpy as np
import pandas as pd

EJERCICIO 1: Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.
- Los valores de la segunda fila y las dos primeras columnas.
- Extraed las filas pares (incluyendo la 0) y todas las columnas.
- Extraed los valores que sean mayores que 0.5.
- Extraed los valores menores que 0.2 o mayores que 0.5

In [19]:
array=np.random.rand(5,3)
array

array([[0.94719152, 0.84663356, 0.02866679],
       [0.89954299, 0.90819148, 0.84979855],
       [0.99164855, 0.67580663, 0.62413185],
       [0.38159012, 0.6501976 , 0.70705876],
       [0.53779576, 0.11273305, 0.84125957]])

In [20]:
print(f"El valor de la primera fila y la segunda columna es: {array[0,1]}")


El valor de la primera fila y la segunda columna es: 0.8466335619265822


In [21]:
print(f"Los valores de la segunda fila y las dos primeras columnas es: {array[1,:2]}")

Los valores de la segunda fila y las dos primeras columnas es: [0.89954299 0.90819148]


In [22]:
print("Las filas pares (incluyendo la 0) y todas las columnas son:")
print(array[::2,])

Las filas pares (incluyendo la 0) y todas las columnas son:
[[0.94719152 0.84663356 0.02866679]
 [0.99164855 0.67580663 0.62413185]
 [0.53779576 0.11273305 0.84125957]]


In [23]:
print("Extraed los valores que sean mayores que 0.5.")
print(array[array>0.5])

Extraed los valores que sean mayores que 0.5.
[0.94719152 0.84663356 0.89954299 0.90819148 0.84979855 0.99164855
 0.67580663 0.62413185 0.6501976  0.70705876 0.53779576 0.84125957]


In [24]:
print("Extraed los valores menores que 0.2 o mayores que 0.5")
print(array[(array<0.2)|(array>0.5)])

Extraed los valores menores que 0.2 o mayores que 0.5
[0.94719152 0.84663356 0.02866679 0.89954299 0.90819148 0.84979855
 0.99164855 0.67580663 0.62413185 0.6501976  0.70705876 0.53779576
 0.11273305 0.84125957]


EJERCICIO 2: Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.
- El segundo de 3 matrices, 2 filas y 5 columnas
- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
- Sumad los dos arrays. ¿Podéis? ¿Por qué?
- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
- .reshape()
- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.


In [25]:
array2=np.random.rand(2,5,3)
array3=np.random.rand(3,2,5)

In [28]:
def propiedades (array):
    print(f"La forma del array: {array.shape}")
    print(f"El tamaño del array: {array.size}")
    print(f"Las dimenciones del array: {array.ndim}")
    print(f"El tipo de dato del array: {array.dtype}")

In [29]:
propiedades(array2)

La forma del array: (2, 5, 3)
El tamaño del array: 30
Las dimenciones del array: 3
El tipo de dato del array: float64


In [30]:
propiedades(array3)

La forma del array: (3, 2, 5)
El tamaño del array: 30
Las dimenciones del array: 3
El tipo de dato del array: float64


In [31]:
array4=np.add(array2,array3)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

R= No se pueden sumar porque tienen diferentes formas.

In [45]:
#Aqui se cambian los ejes del array2 para poder sumarlo con el array3
array_transpose=np.transpose(array2,(2,0,1))

In [52]:
#Se hace la suma
suma_transpose=np.add(array_transpose,array3)

In [53]:
#El resultado
suma_transpose

array([[[0.85851503, 1.03130774, 0.73405326, 1.03871795, 0.33623682],
        [1.14267751, 0.71578134, 0.77696584, 0.43975998, 1.74608719]],

       [[1.52474223, 1.47590816, 1.64410313, 1.42724676, 0.801078  ],
        [1.74252475, 0.04100637, 0.60138682, 0.98161608, 0.4120136 ]],

       [[0.87355819, 0.98832167, 0.69797231, 0.94252069, 1.01393861],
        [1.1593956 , 0.94923708, 0.69139289, 0.90154723, 1.06433301]]])

In [54]:
#Aqui se cambian la forma del array2 para poder sumarlo con el array3
array_reshape=np.reshape(array2,(3,2,5))

In [55]:
#Se hace la suma
suma_reshape=np.add(array_reshape,array3)

In [56]:
#El resultado
suma_reshape

array([[[0.85851503, 1.43692928, 1.01379402, 0.86722668, 1.2038332 ],
        [1.36332293, 0.21960109, 1.14504627, 0.5332184 , 1.58708474]],

       [[1.08650923, 0.89928252, 0.73227207, 1.42941485, 0.44018355],
        [1.67750199, 0.74322567, 0.34746596, 1.61640497, 0.43935218]],

       [[0.57025727, 0.71428742, 0.72884473, 1.15901332, 1.28446163],
        [0.94505389, 1.63716181, 0.94305486, 0.06729331, 1.06433301]]])